#!/usr/bin/env python

"""
This script remaps a given Twist topic into another one, using an anonymous node.
It takes the source and target topics as parameters:
remap_topics [source] [target]
"""

import rospy
import sys
from geometry_msgs.msg import Twist

def receive(data):
  global pub
  pub.publish(data)
  
def main(argv):
  
  global pub

  if len(argv) < 2:
    print 'Usage: remap_topics [Source topic] [Target topic]'
    return

  sourceTopic = str(argv[0])
  targetTopic = str(argv[1])

  print 'Mapping topics: ' + sourceTopic + ' --> ' + targetTopic

  rospy.init_node('mapper_' + sourceTopic.replace('/', '_') + '__' + targetTopic.replace('/', '_'), anonymous=True)
 
  pub = rospy.Publisher(str(argv[1]), Twist, queue_size=10)
  rospy.Subscriber(str(argv[0]), Twist, receive)
  rospy.spin()

if __name__ == "__main__":
  main(sys.argv[1:])
