/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ekumen_tangobot_application_MoveBaseNode */

#ifndef _Included_com_ekumen_tangobot_application_MoveBaseNode
#define _Included_com_ekumen_tangobot_application_MoveBaseNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ekumen_tangobot_application_MoveBaseNode
 * Method:    execute
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ekumen_tangobot_application_MoveBaseNode_execute
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray);

/*
 * Class:     com_ekumen_tangobot_application_MoveBaseNode
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ekumen_tangobot_application_MoveBaseNode_shutdown
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
